apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: dev-front
  labels:
    app: frontend
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: http
    nodePort: 30300
    protocol: TCP
    name: http
  selector:
    app: frontend

