apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless
  namespace: dev-db
  labels:
    app: mongodb
spec:
  clusterIP: None
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
    name: mongodb
  selector:
    app: mongodb

